# Generated by Django 4.1 on 2022-08-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('event', models.ManyToManyField(to='planner.event')),
                ('task', models.ManyToManyField(to='planner.task')),
            ],
        ),
        migrations.DeleteModel(
            name='DailyPlanner',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
