# Generated by Django 4.1 on 2022-08-17 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_tags_delete_dailyplanner_delete_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timeblock',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='event',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='timeblock',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%H:%M'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%H:%M'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='planner.tags'),
        ),
        migrations.AddField(
            model_name='journal',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%H:%M'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%H:%M'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='planner.tags'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Timeblock',
        ),
    ]
