# Generated by Django 4.1 on 2022-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_rename_created_at_journal_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='%d, %m, %Y'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='%d, %m, %Y'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='%d, %m, %Y'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='%d, %m, %Y'),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgent',
            field=models.IntegerField(choices=[(1, 'max priority'), (2, 'urgent'), (3, 'not urgent')], default=2),
        ),
    ]
