# Generated by Django 4.1 on 2022-08-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_remove_event_created_at_remove_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='%d%m%Y'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='%d%m%Y'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='%d%m%Y'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='%d%m%Y'),
        ),
    ]
