# Generated by Django 4.1 on 2022-08-17 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_event_date_alter_event_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%d.%m.%Y,%H:%M'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%d.%m.%Y,%H:%M'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%d.%m.%Y,%H:%M'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%d.%m.%Y,%H:%M'),
        ),
    ]
