# Generated by Django 4.1 on 2022-08-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_remove_event_date_remove_task_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='%d.%m.%Y'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='%d.%m.%Y'),
        ),
    ]
