# Generated by Django 4.1 on 2022-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_remove_journal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
