# Generated by Django 4.1 on 2022-08-20 10:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_journal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
