# Generated by Django 4.1 on 2022-08-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_rename_created_journal_date_of_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
