# Generated by Django 4.1 on 2022-08-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_alter_tags_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_note',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
