# Generated by Django 4.1 on 2022-08-22 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_event_additional_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.AddField(
            model_name='journal',
            name='tags',
            field=models.ManyToManyField(to='planner.tags'),
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%d.%m.%Y,%H:%M'),
        ),
    ]
