# Generated by Django 4.1 on 2022-08-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_remove_task_end_time_remove_task_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='additional_note',
        ),
    ]
