# Generated by Django 4.1 on 2022-08-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_alter_event_end_time_alter_event_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='planner.tags'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='tags',
            field=models.ManyToManyField(blank=True, to='planner.tags'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='planner.tags'),
        ),
    ]
