# Generated by Django 4.1 on 2022-08-27 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_alter_event_description_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date_of_entry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
