# Generated by Django 4.1 on 2022-08-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0024_alter_event_description_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
