# Generated by Django 4.1 on 2022-08-28 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0025_remove_event_cancelled_remove_event_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='planner.tags'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='planner.tags'),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgent',
            field=models.IntegerField(blank=True, choices=[(1, 'max priority'), (2, 'urgent'), (3, 'not urgent')], default=2),
        ),
    ]
